# @package _global_


defaults:
  - _self_
  - model: longformer        # Default model configuration
  - training: default     # Default training configuration
  - hydra: default       # Hydra-specific settings

# Dataset Configuration
datasets:
  _target_: data.CombinedDataset  # Supports multiple datasets
  datasets:
    - _target_: HandsOnMLDataset
      data_dir: data
      dataset_name: hands-on_machine_learning_with_scikit-learn_keras_and_tensorflow
      train_file: train.csv
      validation_file: valid.csv
      test_file: test.csv
      text_column: text
      keyphrases_column: keyphrases
      data_separator: "|"

# Output Configuration
output:
  dir: model_output          # Directory for saving models
  save_total_limit: 1             # Keep only the last checkpoint

# Debug Configuration
debug:
  single_batch: false             # Set to true for quick testing

# Required Run Name
run_name: ???                     # Must be specified via command line
